- name: Allow connections from all IPs
  lineinfile:
    path: "{{ __postgresql_config_path }}/postgresql.conf"
    regexp: '^#?listen_addresses\s*='
    line: "listen_addresses = '*'"
    state: present

- name: Allow all external connections in pg_hba.conf (IPv4 + IPv6)
  blockinfile:
    path: "{{ __postgrsql_pg_hba_conf_path }}"
    block: |
      local   all             all                                     trust
      host    all             all             0.0.0.0/0               trust
      host    all             all             ::/0                    trust
