# - name: Install ntpdate
#   apt:
#     name: ntpdate
#     state: present

# - name: Sync time with time.google.com
#   command: ntpdate -u time.google.com

- name: Ensure gnupg is installed (for apt_key)
  apt:
    name: gnupg
    state: present
    update_cache: yes

- name: add debian postgresql repository
  template:
    src: "deb_repo.list.j2"
    dest: "/etc/apt/sources.list.d/pgdg.list"

- name: add posgresql repository key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Install PostgreSQL on Debian
  apt:
    name: "postgresql-{{ postgres_version }}"
    state: present
    update_cache: yes

- name: Initialize PostgreSQL database
  become: true
  command: "/usr/lib/postgresql/{{ postgres_version }}/bin/initdb"
  args:
    creates: "/var/lib/postgresql/{{ postgres_version }}/main/PG_VERSION"

- name: Install psycopg2
  apt:
    name: python3-psycopg2=2.9.10-1.pgdg120+1
    state: present

- name: Start and enable PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: true

- name: Allow external connections
  include_tasks: allow_external_connections.yml

- name: Restart PostgreSQL to apply config changes
  ansible.builtin.service:
    name: postgresql
    state: restarted
