- name: Ensure gnupg is installed (for apt_key)
  apt:
    name: gnupg
    state: present
    update_cache: yes

- name: Add PostgreSQL GPG key
  get_url:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    dest: /etc/apt/keyrings/postgresql.gpg
    mode: "0644"

- name: Install ntpdate
  apt:
    name: ntpdate
    state: present

- name: Sync system time
  become: true
  ansible.builtin.command: ntpdate time.google.com
  when: ansible_date_time.date is defined # to avoid in check mode

- name: Add PostgreSQL APT repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present
    filename: "pgdg"

- name: Install PostgreSQL on Debian
  apt:
    name: "postgresql-{{ postgres_version }}"
    state: present
    update_cache: yes

- name: Start and enable PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: true
