- name: Install PostgreSQL 17 from official repositories
  hosts: all
  become: true
  vars:
    postgres_version: 17

  tasks:
    - name: Gather OS facts
      setup:

    - name: Install PostgreSQL on AlmaLinux
      include_tasks: tasks/almalinux.yml
      when: ansible_distribution | lower == "almalinux"
      tags: alma_install

    - name: Install PostgreSQL on Debian
      include_tasks: tasks/debian.yml
      when: ansible_os_family == "Debian"
      tags: alma_install
